<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>6502</string>
		<string>asm</string>
		<string>s</string>
	</array>
	<key>name</key>
	<string>6502/BeebAsm Assembly</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#control</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#6502</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#beebasm</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#quotes</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>	
		<dict>
			<key>include</key>
			<string>#labels</string>
		</dict>			
	</array>
	<key>repository</key>
	<dict>
		<key>control</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)((^|\s+)\.error|\s+ert)\b</string>
					<key>name</key>
					<string>keyword.control.error</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)((^|\s+)(\.en)|^(\s+|\S+\s+)(end))\b</string>
					<key>captures</key>
					<dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.control.end</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.control.end</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)((^|\s+)(\.(if|ifdef|ifndef)|#(if|while))|\s+ift|^\s+(eli|els|eif)|^\s*(\.(else|elseif|endif)|#(else|end)))\b</string>
					<key>name</key>
					<string>keyword.control.if</string>
				</dict>
			</array>
		</dict>
		<key>6502</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)(\s+|(?<=:))(adc|and|asl|bcc|bcs|beq|bit|bmi|bne|bpl|brk|bvc|bvs|clc|cld|cli|clv|cmp|cpx|cpy|dec|dex|dey|eor|inc|inx|iny|jmp|jsr|lda|ldx|ldy|lsr|nop|ora|pha|php|pla|plp|rol|ror|rti|rts|sbc|sec|sed|sei|sta|stx|sty|tax|tay|tsx|txa|txs|tya)(?=\.[bzwaqlt]|\s+|[:$#(\\])</string>
					<key>name</key>
					<string>keyword.other.opcode.6502.legal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)(\s+|(?<=:))(stz|phx|phy|plx|ply)(?=\s+|[:$#(])</string>
					<key>name</key>
					<string>keyword.other.opcode.6502.illegal</string>
				</dict>
			</array>
		</dict>
		<key>beebasm</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)(\s+|((^|\s+|(?<=\())))(and|or|eor|mod|div)(?=\.[bzwaqlt]|\s+|[:$#(\\])</string>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)(\s+|((^|\s+|(?<=\())))(cpu|skip|skipto|include|incbin|mapchar|guard|clear|save|for|next|if|elif|else|endif|putfile|putbasic|macro|endmacro)(?=\.[bzwaqlt]|\s+|[:$#(\\])</string>
					<key>name</key>
					<string>keyword</string>
				</dict>		
				<dict>
					<key>match</key>
					<string>(?i)(\s+|((^|\s+|(?<=\())))(equb|equw|equd|equs)(?=\.[bzwaqlt]|\s+|[:$#(\\])</string>
					<key>name</key>
					<string>storage.type</string>
				</dict>		
				<dict>
					<key>match</key>
					<string>(?i)(\s+|((^|\s+|(?<=\())))(org|align)(?=\.[bzwaqlt]|\s+|[:$#(\\])</string>
					<key>name</key>
					<string>storage.modifier</string>
				</dict>									
				<dict>
					<key>match</key>
					<string>(?i)(\s+|((^|\s+|(?<=\())))(true|false|pi|p%)(?=\.[bzwaqlt]|\s+|[:$#(\\])</string>
					<key>name</key>
					<string>constant.regexp</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)(lo|hi|sqr|sin|cos|tan|acs|asn|atn|rad|deg|abs|int|sgn|rnd|not|log|ln|exp)(?=\()\b</string>
					<key>name</key>
					<string>keyword.other.functions</string>
				</dict>		
				<dict>
					<key>match</key>
					<string>(?i)(\s+|((^|\s+|(?<=\())))(print|error)(?=\.[bzwaqlt]|\s+|[:$#(\\])</string>
					<key>name</key>
					<string>keyword.other.debug</string>
				</dict>									
			</array>
		</dict>
		<key>labels</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\.\S+\b</string>
					<key>name</key>
					<string>entity.other.attribute-name.struct</string>
				</dict>
			</array>
		</dict>		
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block</string>
				</dict>
				<dict>
					<key>match</key>
					<string>;.*</string>
					<key>name</key>
					<string>comment.line.semicolon</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.*</string>
					<key>name</key>
					<string>comment.line.back-slash</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^\S*\s*(\*.*)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.line.asterisk</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>quotes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)(?<=,)\s*[xy]\b(?!.*\.reg)</string>
					<key>name</key>
					<string>constant.language.registers</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[+-]?([0-9]*[.])?[0-9]+</string>
					<key>name</key>
					<string>constant.numeric.decimal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\$\b\h+\b|\&\b\h+\b|\b0x\h+\b</string>
					<key>name</key>
					<string>constant.numeric.hexadecimal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>%\b[0-1]+\b</string>
					<key>name</key>
					<string>constant.numeric.binary</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)[+\-*/%!|^=~\:&amp;&lt;&gt;]|equ|\.(and|x?or|not|(lo|hi)(?=\s*\())</string>
					<key>name</key>
					<string>keyword.operators</string>
				</dict>
			</array>
		</dict>
		
	</dict>
	<key>scopeName</key>
	<string>source.asm.6502</string>
	<key>uuid</key>
	<string>150d97b4-3afc-4503-bdfc-c43dd367e79b</string>
</dict>
</plist>
